apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-prod
spec:
  selector:
    matchLabels:
      app: myapp-prod
  replicas: 4
  template:
    metadata:
      labels:
        app: myapp-prod
    spec:
      containers:
      - name: myapp-prod
        image: nanajanashia/argocd-app:1.0
        ports:
        - containerPort: 8080

